### ISSUE TITLE
Abot.Util.RateLimiter.ExitTimerCallback Exception "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by mlemanczyk** [sjdirect/abot#151]
While crawling the websites, the following exception is raised in Abot. Since it's uncaught, it crashes the application completely. The crash happens at random points of the crawling.

We're using MinCrawlDelayPerDomainMilliSeconds = 70 to limit the no. of requests/s. The crawling is on a single domain, but we're downloading few at the same time, using separate instances of the crawlers. Configuration object is re-used, but not shared between domains.

Abot version: 1.5.1.42. We've also tried version 1.5.1.53, but it was crashing the application even more often.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Abot.Util.RateLimiter.ExitTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Would you please be able to fix the issue or recommend a workaround?

**Comment by jirisykora83** [comment]
Do you found any workaround?

**Comment by mlemanczyk** [comment]
Somehow I didn't see GH notification about your comment. I switched to non-async version of even handlers. That seems to work OK in my other project.

**Comment by sjdirect** [comment]
Async event handlers have been removed in version 2.0
