### ISSUE TITLE
Field not found: 'HtmlAgilityPack.HtmlDocument.OptionMaxNestedChildNodes'.

### ISSUE THREAD

**Issue by gyanverma** [sjdirect/abot#171]
Any help on this issue 

Field not found: 'HtmlAgilityPack.HtmlDocument.OptionMaxNestedChildNodes'.

Stack Trace: 
   at Abot.Poco.CrawledPage.InitializeHtmlAgilityPackDocument()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Abot.Core.HapHyperLinkParser.GetHrefValues(CrawledPage crawledPage)
   at Abot.Core.HyperLinkParser.GetLinks(CrawledPage crawledPage)
   at Abot.Crawler.WebCrawler.ParsePageLinks(CrawledPage crawledPage)
   at Abot.Crawler.WebCrawler.ProcessPage(PageToCrawl pageToCrawl)

**Comment by sjdirect** [comment]
Abot uses a patched version of HtmlAgilityPack. That method is only available in that patched version. I assume you have other libs that are installing the nuget version of html agility pack and there is a conflict.
