### ISSUE TITLE
ProtocolViolationException

### ISSUE THREAD

**Issue by poxet** [sjdirect/abot#93]
I get this issue when crawling some domains, for instance this one.
http://www.parkinsonforbundet.se/

**Comment by sjdirect** [comment]
This is happening when HttpWebResponse.LastModified is called and the date is an invalid format. Here is the stacktrace...

[2015-10-16 11:16:33,216] [8  ] [FATAL] - System.Net.ProtocolViolationException: The value of the date string in the header is invalid.
   at System.Net.HttpProtocolUtils.string2date(String S)
   at Abot.Poco.HttpWebResponseWrapper..ctor(HttpWebResponse response) in C:\WorkRoot\Code\abotProjects\abot\Abot\Poco\HttpWebResponseWrapper.cs:line 42
   at Abot.Core.PageRequester.MakeRequest(Uri uri, Func`2 shouldDownloadContent) in C:\WorkRoot\Code\abotProjects\abot\Abot\Core\PageRequester.cs:line 110
   at Abot.Crawler.WebCrawler.CrawlThePage(PageToCrawl pageToCrawl) in C:\WorkRoot\Code\abotProjects\abot\Abot\Crawler\WebCrawler.cs:line 873
   at Abot.Crawler.WebCrawler.ProcessPage(PageToCrawl pageToCrawl) in C:\WorkRoot\Code\abotProjects\abot\Abot\Crawler\WebCrawler.cs:line 671

**Comment by sjdirect** [comment]
Fixed by pull request above
